version: "3"
services:
  app-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=market_promotion
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - app-db